services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $projectDir: '%kernel.project_dir%'

    IntegrationEngine\:
        resource: '../../../'
        exclude:
            - '../../../Infrastructure/Adapter/YamlConfigAdapter.php'
            - '../../../Infrastructure/Http/SymfonyHttpClientAdapter.php'
            - '../../../Core/IntegrationEngine.php'

    integration_engine.cache.default:
        class: IntegrationEngine\Infrastructure\Cache\InMemoryCacheAdapter